version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - checkout
      - .coverage
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test
  lint-and-coverage:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Linter
          command: 
            rfidreader src/
            rfidreader test/
      - run:
          name: Coverage
          command: |
            coverage run
            coverage report
  publish-to-pypi:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - checkout
      - run:
          name: Verify setup.py and changelog
          command: |
            SEMVER="${CIRCLE_TAG:1}"
            grep version='"'$SEMVER'"' setup.py
            grep "## \[$SEMVER\]" CHANGELOG.md
      - run:
          name: Publish to PYPI
          command: |
            pip install twine
            python3 setup.py sdist bdist_wheel
              
workflows:
  main:
    jobs:
     command: |
              pip freeze > requirements.txt
      - store_artifacts:
            paths:
      - build-and-test:
         filters:
            tags:
              only: /.*/
      - lint-and-coverage:
          filters:
            tags:
              only: /.*/
      - publish-to-pypi:
          requires:
            - build-and-test
            - lint-and-coverage
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
